name: LoginProtector
version: '${version}'
main: com.unleqitq.loginProtector.LoginProtector
api-version: '1.21'
authors: [UnleqitQ]
website: https://www.unleqitq.com
depend:
  - ProtocolLib
permissions:
  loginprotector.admin:
    description: Allows the user to use all admin commands
    default: op
